name: Frontend Review

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/frontend-review.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Frontend Review

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v16.13.1
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.1
      - name: Install Node Packages
        run: |
          cd backend
          npm install
      - name: Run Jest
        run: |
          cd backend
          npm test
