name: Lint SQL
on:
  pull_request:
    paths:
      - "database/**"

jobs:
  sqlcheck:
    name: Lint SQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yokawasa/action-sqlcheck@v1.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
