name: Pull Request Review

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-frontend-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List Directory
        run: ls -a
      - name: Run Frontend Reviews
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: my-event
