name: Pull Request Review

on:
  pull_request:
    branches: [main]

jobs:
  run-frontend-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List Directory
        run: ls -a
      - name: Run Frontend Review
        run: gh workflow run ./.github/workflows/frontend-review.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
