name: Pull Request Review

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-frontend-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List Directory
        run: ls -a
      - name: Run Frontend Review
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: my-workflow.yaml
